name: Run mojo unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install modular CLI
      env:
        MODULAR_AUTH: ${{ secrets.MODULAR_AUTH }}
      run: curl https://get.modular.com | MODULAR_AUTH="$MODULAR_AUTH" sh -

    - name: Install mojo CLI
      run: |
        modular install mojo
        export MODULAR_HOME="/home/runner/.modular"
        export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"

    - name: Run tests
      run: mojo run_all_tests.mojo